language: python
python:
  - '3.6'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev

install:
  - sudo apt-get remove -y python-pip  # Removing system pip to avoid conflicts
  - pip uninstall poetry -y
  - curl -sSL https://install.python-poetry.org | python - --version 1.1.15
  - export PATH="$HOME/.local/bin:$PATH"  # Ensure Poetry is available in the PATH
  - poetry --version  # Check Poetry version for debugging

before_script:
  - git clone https://github.com/occ-data/bpadictionary.git
  - cd bpadictionary
  - echo "0.1.0" > VERSION  # Create a VERSION file if it doesn't exist
  - poetry lock --no-update
  - poetry install
  - yes | python setup.py install
  - git clone https://github.com/uc-cdis/dictionaryutils
  - cd dictionaryutils

script:
  - "./run_tests.sh"

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: bpadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: occ-data/bpadictionary
    all_branches: true
