language: python
python:
- '3.6'
install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
  - pip uninstall poetry -y
  - curl -sSL https://install.python-poetry.org | python -
  - export PATH="$HOME/.local/bin:$PATH"
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
- poetry install
- poetry lock
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: bpadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: occ-data/bpadictionary
    all_branches: true
